apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    isDefault: true
    jsonData:
      database: analytics
      defaultDatabase: analytics
      host: clickhouse
      port: 9000
      username: $GRAFANA_CLICKHOUSE_USER
      secure: false
      protocol: native
    secureJsonData:
      password: $GRAFANA_CLICKHOUSE_PASSWORD
    editable: true
