apiVersion: 1

datasources:
  - name: ClickHouse
    type: vertamedia-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    isDefault: true
    jsonData:
      defaultDatabase: analytics
      port: 8123
      server: clickhouse
      username: grafana
      secure: false
    secureJsonData:
      password: ${CLICKHOUSE_PASSWORD}
    editable: true

