apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://$GRAFANA_CLICKHOUSE_HOST:$GRAFANA_CLICKHOUSE_PORT
    isDefault: true
    jsonData:
      database: $GRAFANA_CLICKHOUSE_DB
      defaultDatabase: $GRAFANA_CLICKHOUSE_DB
      host: $GRAFANA_CLICKHOUSE_HOST
      port: 9000
      username: $GRAFANA_CLICKHOUSE_USER
      secure: false
      protocol: native
    secureJsonData:
      password: $GRAFANA_CLICKHOUSE_PASSWORD
    editable: true
