# Docker Compose file for building custom images
# This is used to build images that will be deployed to Docker Swarm
# Docker Swarm doesn't support building images, so we use this file to build them
# Usage: docker-compose -f docker-compose.build.yml build

version: "3.8"

services:
  dbt:
    build:
      context: ../..
      dockerfile: infra/dbt/Dockerfile
    image: beefy-databarn-dbt:latest
    # No need to start the service, just build the image

  superset:
    build:
      context: ../superset
      dockerfile: Dockerfile
    image: beefy-databarn-superset:latest
    # No need to start the service, just build the image

